--MUY FACIL
--1
SELECT * FROM MOVIES

--2
SELECT GENRE_NAME FROM GENRES

--3
SELECT STUDIO_NAME FROM STUDIOS WHERE STUDIO_ACTIVE=1

--4
SELECT * FROM MEMBERS ORDER BY MEMBER_ID DESC LIMIT 20

--FACIL
--5
SELECT MOVIE_DURATION, COUNT(*) 
AS frecuencia 
FROM MOVIES m 
JOIN MEMBERS_MOVIE_RENTAL mf 
ON m.MOVIE_ID = mf.MOVIE_ID
GROUP BY MOVIE_DURATION
ORDER BY frecuencia DESC
LIMIT 20

--6
SELECT MOVIE_NAME
FROM MOVIES
WHERE MOVIE_LAUNCH_DATE > '2000-01-01' 
AND SUBSTRING(MOVIE_NAME, 1, 1) = 'A'

--7
SELECT * FROM ACTORS
WHERE MONTH(ACTOR_BIRTH_DATE) = 6

--8
SELECT * FROM ACTORS
WHERE MONTH(ACTOR_BIRTH_DATE) != 6
AND ACTOR_DEAD_DATE IS NULL

--9
SELECT DIRECTOR_NAME,
DATEDIFF(CURDATE(), DIRECTOR_BIRTH_DATE)/365.25 AS EDAD
FROM DIRECTORS 
WHERE DATEDIFF(CURDATE(), DIRECTOR_BIRTH_DATE)/365.25 <= 50 
AND DIRECTOR_DEAD_DATE IS NULL

--10
SELECT DIRECTOR_NAME,
FLOOR(DATEDIFF(DIRECTOR_DEAD_DATE, DIRECTOR_BIRTH_DATE)/365.25) AS EDAD
FROM DIRECTORS 
WHERE DATEDIFF(DIRECTOR_DEAD_DATE, DIRECTOR_BIRTH_DATE)/365.25 <= 50 
AND DIRECTOR_DEAD_DATE IS NOT NULL

--11
SELECT DIRECTOR_NAME
FROM DIRECTORS 
WHERE DATEDIFF(CURDATE(), DIRECTOR_BIRTH_DATE)/365.25 <= 40 
AND DIRECTOR_DEAD_DATE IS NULL

--12
SELECT AVG(DATEDIFF(CURDATE(), DIRECTOR_BIRTH_DATE) / 365.25) AS EDAD_PROM
FROM DIRECTORS WHERE DIRECTOR_DEAD_DATE IS NULL

--13
SELECT AVG(DATEDIFF(ACTOR_DEAD_DATE, ACTOR_BIRTH_DATE) / 365.25) AS EDAD_PROM
FROM ACTORS WHERE ACTOR_DEAD_DATE IS NOT NULL

--14
SELECT MOVIE_NAME, STUDIO_NAME 
FROM MOVIES
JOIN STUDIOS ON MOVIES.STUDIO_ID = STUDIOS.STUDIO_ID

--15
SELECT * 
FROM MEMBERS
JOIN MEMBERS_MOVIE_RENTAL ON MEMBERS.MEMBER_ID = MEMBERS_MOVIE_RENTAL.MEMBER_ID
WHERE MEMBER_RETURN_DATE < '2015-12-31'
AND MEMBER_RENTAL_DATE > '2010-01-01'

--16
SELECT NATIONALITIES.NATIONALITY_NAME, 
COUNT(MOVIES.MOVIE_ID) AS CANTIDAD
FROM MOVIES 
JOIN NATIONALITIES 
ON MOVIES.NATIONALITY_ID = NATIONALITIES.NATIONALITY_ID
GROUP BY NATIONALITIES.COUNTRY_NAME

--17
SELECT *
FROM MOVIES
JOIN GENRES
ON MOVIES.GENRE_ID = GENRES.GENRE_ID
WHERE GENRES.GENRE_ID = 2

--18
SELECT MOVIES.*
FROM MOVIES
JOIN DIRECTORS 
ON MOVIES.DIRECTOR_ID = DIRECTORS.DIRECTOR_ID
WHERE DIRECTORS.DIRECTOR_BIRTH_DATE > '1980-01-01'
AND DIRECTORS.DIRECTOR_DEAD_DATE IS NULL

--19
SELECT MEMBERS.MEMBER_NAME,
DIRECTORS.DIRECTOR_NAME,
MEMBERS.MEMBER_TOWN AS SAME_TOWN
FROM MEMBERS
JOIN DIRECTORS ON MEMBERS.MEMBER_TOWN =
DIRECTORS.DIRECTOR_BIRTH_PLACE

--20
SELECT MOVIES.MOVIE_NAME,
MOVIES.MOVIE_LAUNCH_DATE
FROM MOVIES
JOIN STUDIOS ON MOVIES.STUDIO_ID = 
STUDIOS.STUDIO_ID
WHERE STUDIOS.STUDIO_ACTIVE = 0

--21
SELECT MOVIES.*
FROM MOVIES
JOIN MEMBERS_MOVIE_RENTAL ON MOVIES.MOVIE_ID = 
MEMBERS_MOVIE_RENTAL.MOVIE_ID
ORDER BY MEMBERS_MOVIE_RENTAL.MEMBER_RENTAL_DATE DESC LIMIT 10

--22
SELECT DIRECTORS.DIRECTOR_NAME,
COUNT(MOVIES.MOVIE_ID) AS CANTIDAD
FROM MOVIES
JOIN DIRECTORS ON MOVIES.DIRECTOR_ID = 
DIRECTORS.DIRECTOR_ID
WHERE DATEDIFF(CURDATE(), DIRECTORS.DIRECTOR_BIRTH_DATE) / 365.25 <= 41
GROUP BY DIRECTORS.DIRECTOR_NAME

--23
SELECT DIRECTORS.DIRECTOR_NAME,
AVG(MOVIES.MOVIE_DURATION) AS DURACION_MEDIA
FROM MOVIES
JOIN DIRECTORS ON MOVIES.DIRECTOR_ID = 
DIRECTORS.DIRECTOR_ID
GROUP BY DIRECTORS.DIRECTOR_NAME

--24
SELECT MOVIES.MOVIE_NAME,
MOVIES.MOVIE_DURATION
FROM MEMBERS_MOVIE_RENTAL
JOIN MOVIES
ON MEMBERS_MOVIE_RENTAL.MOVIE_ID = 
MOVIES.MOVIE_ID
WHERE MEMBER_RENTAL_DATE < '2019-01-25'
AND MEMBER_RENTAL_DATE > '2017-01-25'
ORDER BY MOVIES.MOVIE_DURATION LIMIT 1

--25
SELECT COUNT(MOVIES.MOVIE_ID) AS NUM_PELICULAS
FROM MOVIES
JOIN DIRECTORS 
ON MOVIES.DIRECTOR_ID = 
DIRECTORS.DIRECTOR_ID 
WHERE MOVIES.MOVIE_LAUNCH_DATE > '1960-01-01' 
AND MOVIES.MOVIE_LAUNCH_DATE < '1989-12-31'
AND MOVIES.MOVIE_NAME LIKE '%The%' 
